
version: "3.9"


services:
  database:
    build:
       context: .
       dockerfile: mysql.dockerfile
    container_name: database_c1
    restart: always
    ports:
     - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    environment:
      #MYSQL_USER_FILE: /run/secrets/user
      #MYSQL_PASSWORD_FILE: /run/secrets/user_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      SERVICE_TAGS: testing
      SERVICE_NAME: database
    secrets:
      - mysql_root_pass
    networks:
      draft_network:
        aliases:
          - database_container

 
secrets:
  mysql_root_pass:
    file: ./secrets/mysql_root_pass.txt
volumes:
  docker: {}
networks:
  draft_network:
    name: webserver_net
    driver: bridge
    ipam:
      driver: default
